name: Run dbt on push to main or feature branches

on:
  push:
    branches: 
      - main
      - feature/intermediate
      - feature/staging

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Set up Google credentials
        run: echo '${{ secrets.GCP_KEY }}' > keyfile.json

      - name: Write dbt profile manually
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml <<EOF
          dbt_test:
            target: dev
            outputs:
              dev:
                type: bigquery
                method: service-account
                project: databird-461009
                dataset: dbt_chloe
                keyfile: "${{ github.workspace }}/keyfile.json"
                threads: 1
                timeout_seconds: 300
          EOF

      - name: Install dbt dependencies
        run: dbt deps

      - name: Run dbt models
        run: dbt run

      - name: Run dbt tests
        run: dbt test
