name: Run dbt on push to main

on:
  push:
    branches: [main]

jobs:
  dbt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Set up authentication
        run: |
          echo "${{ secrets.GCP_KEY }}" > keyfile.json

      - name: Write dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILE }}" > ~/.dbt/profiles.yml
        env:
          DBT_PROFILE: ${{ secrets.DBT_PROFILE }}

      - name: Run dbt deps
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/keyfile.json
        run: dbt deps

      - name: Run dbt models
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/keyfile.json
        run: dbt run

      - name: Run dbt tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/keyfile.json
        run: dbt test
